{{ if (include "authelia.traefikCRD.tlsOption.enabled" .) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "authelia.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.ingress.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.ingress.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  minVersion: {{ .Values.ingress.traefikCRD.tlsOptions.minVersion | default "VersionTLS12" }}
  maxVersion: {{ .Values.ingress.traefikCRD.tlsOptions.maxVersion | default "VersionTLS13" }}
  curvePreferences: {{ .Values.ingress.traefikCRD.tlsOptions.curvePreferences }}
  {{- with $suites := .Values.ingress.traefikCRD.tlsOptions.cipherSuites | default (list "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" "TLS_RSA_WITH_AES_256_GCM_SHA384") }}
  cipherSuites: {{ toYaml $suites | nindent 4 }}
  {{- end }}
  sniStrict: {{ .Values.ingress.traefikCRD.tlsOptions.sniStrict }}
{{- end -}}