{{- if (include "authelia.configMap.generate" .) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.name" . }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.configMap.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.configMap.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.configMap.key | default "configuration.yaml" }}: |
    ---
    {{- if (include "authelia.secrets.certificates.enabled" .) }}
    certificates_directory: /certificates
    {{- end }}
    theme: {{ .Values.configMap.theme | default "light" }}
    default_redirection_url: {{ .Values.configMap.default_redirection_url | default (printf "https://www.%s" .Values.domain) }}
    {{- if semverCompare ">=4.35.0" (include "authelia.version" .) }}
    default_2fa_method: {{ .Values.configMap.default_2fa_method | default "" | quote }}
    {{- end }}
    server:
      host: 0.0.0.0
      port: {{ .Values.configMap.server.port | default 9091 }}
      path: {{ .Values.configMap.server.path | default "" | squote }}
      {{- if semverCompare ">=4.33.0" (include "authelia.version" .) }}
      asset_path: {{ .Values.configMap.server.asset_path | default "" | quote }}
      {{- end }}
      {{- if (semverCompare ">=4.34.0" (include "authelia.version" .)) }}
      headers:
        csp_template: {{ .Values.configMap.server.headers.csp_template | default "" | squote }}
      {{- end }}
      read_buffer_size: {{ .Values.configMap.server.read_buffer_size | default 4096 }}
      write_buffer_size: {{ .Values.configMap.server.write_buffer_size | default 4096 }}
      enable_pprof: {{ .Values.configMap.server.enable_pprof | default false }}
      enable_expvars: {{ .Values.configMap.server.enable_expvars | default false }}
    log:
      level: {{ .Values.configMap.log.level | default "info" | squote }}
      format: {{ .Values.configMap.log.format | default "text" | squote }}
      file_path: {{ .Values.configMap.log.file_path | default "" | squote }}
      keep_stdout: true
    {{- if and (semverCompare ">=4.36.0" (include "authelia.version" .)) .Values.configMap.telemetry.metrics.enabled }}
    telemetry:
      metrics:
        enabled: {{ .Values.configMap.telemetry.metrics.enabled | default false }}
        address: '0.0.0.0:{{ .Values.configMap.telemetry.metrics.port | default 9959 }}'
    {{- end }}
    totp:
      {{- if semverCompare ">=4.34.0" (include "authelia.version" .) }}
      disable: {{ .Values.configMap.totp.disable | default false }}
      {{- end }}
      issuer: {{ .Values.configMap.totp.issuer | default .Values.domain }}
      {{- if semverCompare ">=4.33.0" (include "authelia.version" .) }}
      algorithm: {{ .Values.configMap.totp.algorithm | default "sha1" }}
      digits: {{ .Values.configMap.totp.digits | default 6 }}
      {{- end }}
      period: {{ .Values.configMap.totp.period | default 30 }}
      skew: {{ .Values.configMap.totp.skew | default 1 }}
      {{- if semverCompare ">=4.35.0" (include "authelia.version" .) }}
      secret_size: {{ .Values.configMap.totp.secret_size | default 32 }}
      {{- end }}
    {{- if semverCompare ">=4.34.0" (include "authelia.version" .) }}
    webauthn:
      disable: {{ .Values.configMap.webauthn.disable | default false }}
      display_name: {{ .Values.configMap.webauthn.display_name | default "Authelia" }}
      attestation_conveyance_preference: {{ .Values.configMap.webauthn.attestation_conveyance_preference | default "indirect" }}
      user_verification: {{ .Values.configMap.webauthn.user_verification | default "preferred" }}
      timeout: {{ .Values.configMap.webauthn.timeout | default "60s" }}
    {{- end }}
    {{- if semverCompare ">=4.31.0" (include "authelia.version" .) }}
    ntp:
      address: {{ .Values.configMap.ntp.address | default "time.cloudflare.com:123" }}
      version: {{ .Values.configMap.ntp.version | default 3 }}
      max_desync: {{ .Values.configMap.ntp.max_desync | default "3s" }}
      disable_startup_check: {{ .Values.configMap.ntp.disable_startup_check | default false }}
      disable_failure: {{ .Values.configMap.ntp.disable_failure | default false }}
    {{- end }}
    {{- if include "authelia.duo.enabled" . }}
    duo_api:
      hostname: {{ .Values.configMap.duo_api.hostname }}
      integration_key: {{ .Values.configMap.duo_api.integration_key }}
      {{- if semverCompare ">=4.33.0" (include "authelia.version" .) }}
      enable_self_enrollment: {{ .Values.configMap.duo_api.enable_self_enrollment | default false }}
      {{- end }}
    {{- end }}
    {{- with $auth := .Values.configMap.authentication_backend }}
    authentication_backend:
      {{- if semverCompare "<4.36.0" (include "authelia.version" $) }}
      disable_reset_password: {{ include "authelia.config.password_reset.disable" $ }}
      {{- end }}
      {{- if semverCompare ">=4.35.0" (include "authelia.version" $) }}
      password_reset:
        {{- if semverCompare ">=4.36.1" (include "authelia.version" $) }}
        disable: {{ include "authelia.config.password_reset.disable" $ }}
        {{- end }}
        custom_url: {{ $auth.password_reset.custom_url | default "" | quote }}
      {{- end }}
      {{- if $auth.file.enabled }}
      file:
        path: {{ $auth.file.path }}
        password: {{ toYaml $auth.file.password | nindent 10 }}
      {{- end }}
      {{- if $auth.ldap.enabled }}
      ldap:
        implementation: {{ $auth.ldap.implementation | default "custom" }}
        url: {{ $auth.ldap.url }}
        timeout: {{ $auth.ldap.timeout | default "5s" }}
        start_tls: {{ $auth.ldap.start_tls }}
        tls:
          {{- if $auth.ldap.tls.server_name }}
          server_name: {{ $auth.ldap.tls.server_name }}
          {{- end }}
          minimum_version: {{ $auth.ldap.tls.minimum_version | default "TLS1.2" }}
          skip_verify: {{ $auth.ldap.tls.skip_verify | default false }}
        {{- if $auth.ldap.base_dn }}
        base_dn: {{ $auth.ldap.base_dn }}
        {{- end }}
        {{- if $auth.ldap.username_attribute }}
        username_attribute: {{ $auth.ldap.username_attribute }}
        {{- end }}
        {{- if $auth.ldap.additional_users_dn }}
        additional_users_dn: {{ $auth.ldap.additional_users_dn }}
        {{- end }}
        {{- if $auth.ldap.users_filter }}
        users_filter: {{ $auth.ldap.users_filter }}
        {{- end }}
        {{- if $auth.ldap.additional_groups_dn }}
        additional_groups_dn: {{ $auth.ldap.additional_groups_dn }}
        {{- end }}
        {{- if $auth.ldap.groups_filter }}
        groups_filter: {{ $auth.ldap.groups_filter }}
        {{- end }}
        {{- if $auth.ldap.group_name_attribute }}
        group_name_attribute: {{ $auth.ldap.group_name_attribute }}
        {{- end }}
        {{- if $auth.ldap.mail_attribute }}
        mail_attribute: {{ $auth.ldap.mail_attribute }}
        {{- end }}
        {{- if $auth.ldap.display_name_attribute }}
        display_name_attribute: {{ $auth.ldap.display_name_attribute }}
        {{- end }}
        {{- if semverCompare ">=4.35.2" (include "authelia.version" $) }}
        permit_referrals: {{ $auth.ldap.permit_referrals }}
        {{- end }}
        {{- if semverCompare ">=4.36.0" (include "authelia.version" $) }}
        permit_unauthenticated_bind: {{ $auth.ldap.permit_unauthenticated_bind }}
        {{- end }}
        user: {{ $auth.ldap.user }}
      {{- end }}
    {{- end }}
    {{- if semverCompare ">=4.35.0" (include "authelia.version" .) }}
    password_policy:
      standard:
        enabled: {{ .Values.configMap.password_policy.standard.enabled }}
        min_length: {{ .Values.configMap.password_policy.standard.min_length }}
        max_length: {{ .Values.configMap.password_policy.standard.max_length }}
        require_uppercase: {{ .Values.configMap.password_policy.standard.require_uppercase }}
        require_lowercase: {{ .Values.configMap.password_policy.standard.require_lowercase }}
        require_number: {{ .Values.configMap.password_policy.standard.require_number }}
        require_special: {{ .Values.configMap.password_policy.standard.require_special }}
      zxcvbn:
        enabled: {{ .Values.configMap.password_policy.zxcvbn.enabled }}
        min_score: {{ .Values.configMap.password_policy.zxcvbn.min_score }}
    {{- end }}
    {{- with $session := .Values.configMap.session }}
    session:
      name: {{ $session.name | default "authelia_session" }}
      domain: {{ $.Values.domain | required "A valid .Values.domain entry required!" }}
      same_site: {{ $session.same_site | default "lax" }}
      expiration: {{ $session.expiration | default "1M"}}
      inactivity: {{ $session.inactivity | default "5m" }}
      remember_me_duration: {{ $session.remember_me_duration | default "1M" }}
      {{- if $session.redis.enabled }}
      redis:
        host: {{ $session.redis.host }}
        port: {{ $session.redis.port | default 6379 }}
        {{- if $session.redis.username }}
        username: {{ $session.redis.username }}
        {{- end }}
        maximum_active_connections: {{ $session.redis.maximum_active_connections | default 8 }}
        minimum_idle_connections: {{ $session.redis.minimum_idle_connections | default 0 }}
        {{- if $session.redis.tls.enabled }}
        tls:
          {{- if $session.redis.tls.server_name }}
          server_name: {{ $session.redis.tls.server_name }}
          {{- end }}
          minimum_version: {{ $session.redis.tls.minimum_version | default "TLS1.2" }}
          skip_verify: {{ $session.redis.tls.skip_verify | default false }}
        {{- end }}
        {{- if $session.redis.high_availability.enabled }}
        high_availability:
          sentinel_name: {{ $session.redis.high_availability.sentinel_name }}
          {{- if $session.redis.high_availability.nodes }}
          nodes: {{ toYaml $session.redis.high_availability.nodes | nindent 10 }}
          {{- end }}
          {{- if semverCompare ">=4.34.5" (include "authelia.version" $) }}
          sentinel_username: {{ $session.redis.high_availability.username | default "" | squote }}
          {{- end }}
          route_by_latency: {{ $session.redis.high_availability.route_by_latency }}
          route_randomly: {{ $session.redis.high_availability.route_randomly }}
        {{- end }}
      {{- end }}
    {{- end }}
    regulation: {{ toYaml .Values.configMap.regulation | nindent 6 }}
    storage:
      {{- with $storage := .Values.configMap.storage }}
      {{- if $storage.local.enabled }}
      local:
        path: {{ $storage.local.path }}
      {{- end }}
      {{- if $storage.mysql.enabled }}
      mysql:
        host: {{ $storage.mysql.host | squote }}
        port: {{ $storage.mysql.port | default 3306 }}
        database: {{ $storage.mysql.database | default "authelia" | squote }}
        username: {{ $storage.mysql.username | default "authelia" | squote }}
        {{- if semverCompare ">=4.31.0" (include "authelia.version" $) }}
        timeout: {{ $storage.mysql.timeout | default "5s" }}
        {{- end }}
      {{- end }}
      {{- if $storage.postgres.enabled }}
      postgres:
        host: {{ $storage.postgres.host | squote }}
        port: {{ $storage.postgres.port | default 5432 }}
        database: {{ $storage.postgres.database | default "authelia" | squote }}
        {{- if semverCompare ">=4.33.0" (include "authelia.version" $) }}
        schema: {{ $storage.postgres.schema | default "public" | squote }}
        {{- end }}
        username: {{ $storage.postgres.username | default "authelia" | squote }}
        {{- if semverCompare ">=4.31.0" (include "authelia.version" $) }}
        timeout: {{ $storage.postgres.timeout | default "5s" }}
        {{- end }}
        {{- if semverCompare ">=4.33.0" (include "authelia.version" $) }}
        ssl:
          mode: {{ $storage.postgres.sslmode | default "disable" | squote }}
          root_certificate: {{ $storage.postgres.ssl.root_certificate | default "" | squote }}
          certificate: {{ $storage.postgres.ssl.certificate | default "" | squote }}
          key: {{ $storage.postgres.ssl.key | default "" | squote }}
        {{- else }}
        sslmode: {{ $storage.postgres.ssl.mode | default "disable" | squote }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with $notifier := .Values.configMap.notifier }}
    notifier:
      disable_startup_check: {{ $.Values.configMap.notifier.disable_startup_check }}
      {{- if $notifier.filesystem.enabled }}
      filesystem:
        filename: {{ $notifier.filesystem.filename }}
      {{- end }}
      {{- if $notifier.smtp.enabled }}
      smtp:
        host: {{ $notifier.smtp.host | squote }}
        port: {{ $notifier.smtp.port | default 25 }}
        {{- if semverCompare ">=4.31.0" (include "authelia.version" $) }}
        timeout: {{ $notifier.smtp.timeout | default "5s" }}
        {{- end }}
        username: {{ $notifier.smtp.username | default "" | squote }}
        sender: {{ $notifier.smtp.sender | default "" | squote }}
        identifier: {{ $notifier.smtp.identifier | default "localhost" | squote }}
        subject: {{ $notifier.smtp.subject | squote }}
        startup_check_address: {{ $notifier.smtp.startup_check_address | squote }}
        disable_require_tls: {{ $notifier.smtp.disable_require_tls | default false }}
        disable_html_emails: {{ $notifier.smtp.disable_html_emails | default false }}
        tls:
          {{- if $notifier.smtp.tls.server_name }}
          server_name: {{ $notifier.smtp.tls.server_name }}
          {{- end }}
          minimum_version: {{ $notifier.smtp.tls.minimum_version | default "TLS1.2" }}
          skip_verify: {{ $notifier.smtp.tls.skip_verify | default false }}
      {{- end }}
    {{- end }}
    {{- if .Values.configMap.identity_providers.oidc.enabled }}
    identity_providers:
      oidc:
        access_token_lifespan: {{ .Values.configMap.identity_providers.oidc.access_token_lifespan | default "1h" }}
        authorize_code_lifespan: {{ .Values.configMap.identity_providers.oidc.authorize_code_lifespan | default "1m" }}
        id_token_lifespan: {{ .Values.configMap.identity_providers.oidc.id_token_lifespan | default "1h" }}
        refresh_token_lifespan: {{ .Values.configMap.identity_providers.oidc.refresh_token_lifespan | default "90m" }}
        {{- if semverCompare ">=4.34.1" (include "authelia.version" .) }}
        enforce_pkce: {{ .Values.configMap.identity_providers.oidc.enforce_pkce | default "public_clients_only" }}
        enable_pkce_plain_challenge: {{ .Values.configMap.identity_providers.oidc.enable_pkce_plain_challenge | default false }}
        {{- end }}
        enable_client_debug_messages: {{ .Values.configMap.identity_providers.oidc.enable_client_debug_messages | default false }}
        minimum_parameter_entropy: {{ .Values.configMap.identity_providers.oidc.minimum_parameter_entropy | default 8 }}
        {{- if semverCompare ">=4.35.0" (include "authelia.version" $) }}
        cors:
          {{- if .Values.configMap.identity_providers.oidc.cors.endpoints }}
          endpoints: {{ toYaml .Values.configMap.identity_providers.oidc.cors.endpoints | nindent 12 }}
          {{- end }}
          {{- if .Values.configMap.identity_providers.oidc.cors.allowed_origins }}
          allowed_origins: {{ toYaml .Values.configMap.identity_providers.oidc.cors.allowed_origins | nindent 12 }}
          {{- end }}
          allowed_origins_from_client_redirect_uris: {{ .Values.configMap.identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris }}
        {{- end }}
        {{- if and .Values.configMap.identity_providers.oidc.clients (gt (len .Values.configMap.identity_providers.oidc.clients) 0) }}
        clients:
        {{- range $client := .Values.configMap.identity_providers.oidc.clients }}
        - id: {{ $client.id }}
          description: {{ $client.description | default $client.id }}
          {{- if not $client.public }}
          secret: {{ $client.secret | default (randAlphaNum 128) }}
          {{- end }}
          {{- if semverCompare ">=4.35.0" (include "authelia.version" $) }}
          sector_identifier: {{ $client.sector_identifier | default "" | quote }}
          {{- if $client.pre_configured_consent_duration }}
          pre_configured_consent_duration: {{ $client.pre_configured_consent_duration | quote }}
          {{- end }}
          {{- end }}
          public: {{ $client.public | default false }}
          authorization_policy: {{ $client.authorization_policy | default "two_factor" }}
          {{- if $client.redirect_uris }}
          redirect_uris: {{ toYaml $client.redirect_uris | nindent 10 }}
          {{- end }}
          {{- if $client.audience }}
          audience: {{ toYaml $client.audience | nindent 10 }}
          {{- end }}
          scopes: {{ toYaml ($client.scopes | default (list "openid" "profile" "email" "groups")) | nindent 10 }}
          grant_types: {{ toYaml ($client.grant_types | default (list "refresh_token" "authorization_code")) | nindent 10 }}
          response_types: {{ toYaml ($client.response_types | default (list "code")) | nindent 10 }}
          {{- if hasKey $client "response_modes" }}
          response_modes: {{ toYaml $client.response_modes | nindent 10 }}
          {{- end }}
          userinfo_signing_algorithm: {{ $client.userinfo_signing_algorithm | default "none" }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- if not (include "authelia.secrets.acl.mount" .) }}
    {{- tpl (.Files.Get "files/configuration.acl.yaml") . | trim | nindent 4 }}
    {{- end }}
    ...
{{- end }}
