---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.name" . }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.service.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.service.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- with $ips := .Values.service.externalIPs }}
  externalIPs: {{ toYaml $ips | nindent 4 }}
  {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  selector: {{- include "authelia.labels.match" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      protocol: TCP
      port: {{ include "authelia.service.port" . }}
      targetPort: http
    {{- if and (semverCompare ">=4.36.0" (include "authelia.version" .)) .Values.configMap.telemetry.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.configMap.telemetry.metrics.port | default 9959 }}
      targetPort: metrics
    {{- end }}